name: Deploy Private GitHub Repository to cPanel
on:
  push:
    branches:
      - main

jobs:
  FTP-Deploy-Action:
    name: FTP-Deploy-Action
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Upload only dist folder
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ftp.onetapcard.uk
          username: u723786238.tamandeep1
          password: "^VK*aBQF/:IyiW4g"
          local-dir: dist/
          server-dir: public_html/
